### ISSUE TITLE
Query for 2 tags with OR statement

### ISSUE THREAD

**Issue by lorenzvs** [younata/SwiftOpenStreetMap#5]
Due to OSM tags being inconsistent, I would like to query for 2 tags with an OR statement.

I want to retrieve the nodes tagged with `"amenity"="drinking_water"` or `"drinking_water"="yes"`.

[Example query](https://overpass-turbo.eu/s/1gZg) 

Would it be possible to recreate this query with your package? 🤔

I tried the following code but it only returns nodes that has both keys and values:

`let tags: Set<Tag> = [.hasValue(key: "amenity", value: "drinking_water"),.hasValue(key: "drinking_water", value: "yes")]`

Thanks again for creating this package. Without your work, I would not have been able to ship my [Fountain Finder App](https://apps.apple.com/us/app/fountain-finder/id1515767527)! 🙏

**Comment by younata** [comment]
Thanks for the feedback! Also, that's a really neat and useful little app!

With the current structure of the library, you could add your own builder in between the other builder functions, which creates the union for you. Something like:

```swift
func unionedQuery(queries: [String]) -> String {
    let joinedQueries = queries.joined(separator: ";")
    return "(\(joinedQueries)");"
}
```

And used like:

```swift
overpassService.query(
    unionedQuery([
        nodeQuery(boundingBox: box, tags: [.hasValue(key: "amenity", value: "drinking_water")]),
        nodeQuery(boundingBox: box, tags: [.hasValue(key: "drinking_water", value: "yes")])
    ])
)
```

I'll probably add it to the library proper later. This library could certainly use some modernization.

**Comment by lorenzvs** [comment]
Thanks a million for the quick solution, it works now! 🙌

I had to change your example slightly to:

```
    func unionedQuery(queries: [String]) -> String {
        let joinedQueries = queries.joined(separator: "")
        return "(\(joinedQueries))"
    }
```

I created the app for my own need: avoiding buying plastic water bottles while exploring cities here in Europe. Hope it's also valuable in the US! 😊
